### ISSUE TITLE
Outdated database schema

### ISSUE THREAD

**Issue by crazier9527** [kuklinistvan/docker-anki-sync-server#7]
ankisyncd.conf found
auth.db found
collections directory exists
Starting tsudoko's anki-sync-server
[2019-08-11 12:22:26,842]:INFO:ankisyncd:Loaded config from /app/anki-sync-server/ankisyncd.conf
[2019-08-11 12:22:26,842]:INFO:ankisyncd.users:Found auth_db_path in config, using SqliteUserManager for auth
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/app/anki-sync-server/ankisyncd/__main__.py", line 11, in <module>
    ankisyncd.sync_app.main()
  File "/app/anki-sync-server/ankisyncd/sync_app.py", line 663, in main
    ankiserver = SyncApp(config)
  File "/app/anki-sync-server/ankisyncd/sync_app.py", line 401, in __init__
    self.user_manager = get_user_manager(config)
  File "/app/anki-sync-server/ankisyncd/users.py", line 202, in get_user_manager
    return SqliteUserManager(config['auth_db_path'], config['data_root'])
  File "/app/anki-sync-server/ankisyncd/users.py", line 49, in __init__
    self._ensure_schema_up_to_date()
  File "/app/anki-sync-server/ankisyncd/users.py", line 63, in _ensure_schema_up_to_date
    raise Exception("Outdated database schema, run utils/migrate_user_tables.py")
Exception: Outdated database schema, run utils/migrate_user_tables.py

**Comment by kuklinistvan** [comment]
Hey there!

The exception you have encountered seems to tell what there is to do:

```
Exception: Outdated database schema, run utils/migrate_user_tables.py
```
(this is the last line of your report)

Please make a backup copy of your Anki data, then perform the database upgrading by accessing the shell of the container.

```
host$ docker exec -it anki-container sh
/app/anki-sync-server # ./utils/migrate_user_tables.py
```
 
The reason you have to do this is that `ankisyncd` was updated since then and the database scheme has changed. After migration you are ready to continue using it.

**Comment by kuklinistvan** [comment]
Sorry, I'm closing this for now due to inactivity. Feel free to reopen if you have further questions.
